### ISSUE TITLE
Cannot get the hash file correctly

### ISSUE THREAD

**Issue by xiaods** [MCJack123/ghaction-Generate-Release-Hashes#3]
I follow the README config, but the github action can't get the hash file.

https://github.com/xiaods/k8e/blob/master/.github/workflows/release.yml#L32

do you do me a favor?

**Comment by MCJack123** [comment]
The OP's already resolved this, but for anyone else with this issue:

This tool is meant for generating hashes for pre-existing release assets - either upload the assets first (and use the new `get-assets` option to update the list), or generate the list manually using `shasum` with local files instead.
